<template>
  <div class="mode-selector">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <!-- 模式A：從題庫選題 -->
      <button
        @click="selectMode('select')"
        :class="[
          'mode-card',
          modelValue === 'select' ? 'active' : 'inactive'
        ]"
      >
        <div class="mode-icon">📚</div>
        <div class="mode-title">{{ t('examPaper.selectFromLibrary') || '從題庫選題' }}</div>
        <div class="mode-description">
          {{ t('examPaper.selectFromLibraryDesc') || '從已有題目中篩選和選擇，適合使用現有題庫' }}
        </div>
        <div v-if="modelValue === 'select'" class="mode-badge">✓ 已選擇</div>
      </button>

      <!-- 模式B：AI 自動生成 -->
      <button
        @click="selectMode('generate')"
        :class="[
          'mode-card',
          modelValue === 'generate' ? 'active' : 'inactive'
        ]"
      >
        <div class="mode-icon">🤖</div>
        <div class="mode-title">{{ t('examPaper.aiAutoGenerate') || 'AI 自動生成' }}</div>
        <div class="mode-description">
          {{ t('examPaper.aiAutoGenerateDesc') || '根據配置自動生成新題目，適合快速創建考券' }}
        </div>
        <div v-if="modelValue === 'generate'" class="mode-badge">✓ 已選擇</div>
      </button>
    </div>
  </div>
</template>

<script setup>
import { useLanguage } from '../../composables/useLanguage.js'

const { t } = useLanguage()

const props = defineProps({
  modelValue: {
    type: String,
    required: true,
    validator: (value) => ['select', 'generate'].includes(value)
  }
})

const emit = defineEmits(['update:modelValue'])

const selectMode = (mode) => {
  emit('update:modelValue', mode)
}
</script>

<style scoped>
.mode-selector {
  width: 100%;
}

.mode-card {
  position: relative;
  padding: 1.5rem;
  border-radius: 0.5rem;
  text-align: left;
  transition: all 0.2s ease;
  cursor: pointer;
  width: 100%;
}

.mode-card.inactive {
  background-color: #f9fafb;
  border: 2px solid #e5e7eb;
}

.mode-card.inactive:hover {
  background-color: #f3f4f6;
  border-color: #d1d5db;
  transform: translateY(-2px);
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}

.mode-card.active {
  background-color: #eff6ff;
  border: 2px solid #3b82f6;
  box-shadow: 0 4px 6px -1px rgba(59, 130, 246, 0.1);
}

.mode-icon {
  font-size: 2.5rem;
  margin-bottom: 0.75rem;
}

.mode-title {
  font-size: 1.125rem;
  font-weight: 600;
  color: #111827;
  margin-bottom: 0.5rem;
}

.mode-description {
  font-size: 0.875rem;
  color: #6b7280;
  line-height: 1.5;
}

.mode-badge {
  position: absolute;
  top: 1rem;
  right: 1rem;
  background-color: #3b82f6;
  color: white;
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
  font-size: 0.75rem;
  font-weight: 500;
}
</style>
