<template>
  <div class="w-full">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <!-- 模式A：從題庫選題 -->
      <button
        @click="selectMode('select')"
        class="relative p-6 rounded-lg text-left transition-all duration-200 cursor-pointer w-full"
        :class="modelValue === 'select'
          ? 'bg-primary-50 border-2 border-primary-500 shadow-[0_4px_6px_-1px_rgba(59,130,246,0.1)]'
          : 'bg-gray-50 border-2 border-gray-200 hover:bg-gray-100 hover:border-gray-300 hover:-translate-y-0.5 hover:shadow-[0_4px_6px_-1px_rgba(0,0,0,0.1)]'"
      >
        <div class="text-[2.5rem] mb-3">📚</div>
        <div class="text-lg font-semibold text-gray-900 mb-2">{{ t('examPaper.selectFromLibrary') || '從題庫選題' }}</div>
        <div class="text-sm text-gray-500 leading-normal">
          {{ t('examPaper.selectFromLibraryDesc') || '從已有題目中篩選和選擇，適合使用現有題庫' }}
        </div>
        <div v-if="modelValue === 'select'" class="absolute top-4 right-4 bg-primary-500 text-white px-3 py-1 rounded-full text-xs font-medium">✓ 已選擇</div>
      </button>

      <!-- 模式B：AI 自動生成 -->
      <button
        @click="selectMode('generate')"
        class="relative p-6 rounded-lg text-left transition-all duration-200 cursor-pointer w-full"
        :class="modelValue === 'generate'
          ? 'bg-primary-50 border-2 border-primary-500 shadow-[0_4px_6px_-1px_rgba(59,130,246,0.1)]'
          : 'bg-gray-50 border-2 border-gray-200 hover:bg-gray-100 hover:border-gray-300 hover:-translate-y-0.5 hover:shadow-[0_4px_6px_-1px_rgba(0,0,0,0.1)]'"
      >
        <div class="text-[2.5rem] mb-3">🤖</div>
        <div class="text-lg font-semibold text-gray-900 mb-2">{{ t('examPaper.aiAutoGenerate') || 'AI 自動生成' }}</div>
        <div class="text-sm text-gray-500 leading-normal">
          {{ t('examPaper.aiAutoGenerateDesc') || '根據配置自動生成新題目，適合快速創建考券' }}
        </div>
        <div v-if="modelValue === 'generate'" class="absolute top-4 right-4 bg-primary-500 text-white px-3 py-1 rounded-full text-xs font-medium">✓ 已選擇</div>
      </button>
    </div>
  </div>
</template>

<script setup>
import { useLanguage } from '../../composables/useLanguage.js'

const { t } = useLanguage()

const props = defineProps({
  modelValue: {
    type: String,
    required: true,
    validator: (value) => ['select', 'generate'].includes(value)
  }
})

const emit = defineEmits(['update:modelValue'])

const selectMode = (mode) => {
  emit('update:modelValue', mode)
}
</script>
